import axios from "axios";
import Head from "next/head";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";
import { getuserDataByToken } from "../server/routes/userAuth";
import { useSelector, useDispatch } from "react-redux";
import { setUserAuth } from "../store/index";
import { showLoader } from "../store/index";
import { show } from "./register";
import { useRouter } from "next/router";
import HomePage from "../src/components/Home/HomePage";
import { getproductData } from "../server/routes/productData";
function Home(props) {
  const userDetail = useSelector((state) => state.userAuth);
  const router = useRouter();
  const dispatch = useDispatch();
  const userAuthCheck = async (cookie) => {
    dispatch(showLoader(true));
    const response = await getuserDataByToken("auth/getUserData", cookie);

    if (JSON.parse(response).err) {
      dispatch(showLoader(false));
      // router.push("/signin");
      return show("Sorry ! ", JSON.parse(response).err, "bg-red-500");
    }
    // console.log();
    dispatch(setUserAuth(JSON.parse(response)));
    dispatch(showLoader(false));
  };
  useEffect(() => {
    userAuthCheck(props.cookies);
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>E-Commerce App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HomePage products={props.productdata} />
      </main>
    </div>
  );
}
export const getServerSideProps = async ({ req, res }) => {
  const response = await getproductData("product/getproductdata");

  return { props: { cookies: req.cookies, productdata: response } };
};

// export const getServerSideProps = async ({ req, res }) => {
//   return { props: "" };
// };

export default Home;
